### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by kminvita** [kminvita/seb_fe_44_todoapp#2]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 메모 생성 기능
2. [ ] 메모 수정 기능
3. [ ] 메모 삭제 기능

### 예상 작업 시간
3h

**Comment by kminvita** [comment]
생성 기능 >  삭제기능 >  수정기능 순으로 만들져 레츠고
